export const CLOTHING_TYPES = [
  "Shirt",
  "T-shirt",
  "Blouse",
  "Sweater",
  "Hoodie",
  "Jacket",
  "Coat",
  "Pants",
  "Jeans",
  "Shorts",
  "Skirt",
  "Dress",
  "Suit",
  "Blazer",
  "Vest",
  "Sweatpants",
  "Joggers",
  "Leggings",
  "Cardigan",
  "Tank Top",
  "Polo Shirt",
  "Swimsuit",
  "Scarf",
  "Hat",
  "Gloves",
  "Socks",
  "Shoes",
  "Sandals",
  "Boots",
  "Sneakers",
  "Heels",
  "Flats",
  "Flip-Flops",
];

export const CLOTHING_COLORS = [
  {
    id: 1,
    name: "Black",
    color: "bg-slate-900",
    hex: "#000000",
    value: "black",
  },
  { id: 2, name: "White", color: "bg-white", hex: "#FFFFFF", value: "white" },
  { id: 3, name: "Gray", color: "bg-slate-500", hex: "#808080", value: "gray" },
  { id: 4, name: "Navy Blue", color: "bg-blue-800", hex: "#000080" },
  { id: 5, name: "Blue", color: "bg-blue-500", hex: "#0000FF" },
  { id: 6, name: "Sky Blue", color: "bg-blue-300", hex: "#87CEEB" },
  { id: 7, name: "Red", color: "bg-red-500", hex: "#FF0000" },
  { id: 8, name: "Maroon", color: "bg-red-800", hex: "#800000" },
  { id: 9, name: "Pink", color: "bg-pink-400", hex: "#FFC0CB" },
  { id: 10, name: "Hot Pink", color: "bg-pink-500", hex: "#FF69B4" },
  { id: 11, name: "Purple", color: "bg-purple-500", hex: "#800080" },
  { id: 12, name: "Lavender", color: "bg-purple-300", hex: "#E6E6FA" },
  { id: 13, name: "Green", color: "bg-green-500", hex: "#008000" },
  { id: 14, name: "Olive Green", color: "bg-green-800", hex: "#556B2F" },
  { id: 15, name: "Yellow", color: "bg-yellow-400", hex: "#FFFF00" },
  { id: 16, name: "Orange", color: "bg-orange-500", hex: "#FFA500" },
  { id: 17, name: "Brown", color: "bg-stone-800", hex: "#8B4513" },
  { id: 18, name: "Beige", color: "bg-slate-200", hex: "#F5F5DC" },
  { id: 19, name: "Cream", color: "bg-slate-100", hex: "#FFFDD0" },
  { id: 20, name: "Teal", color: "bg-primary-600", hex: "#008080" },
  { id: 21, name: "Turquoise", color: "bg-teal-400", hex: "#40E0D0" },
  { id: 22, name: "Gold", color: "bg-yellow-500", hex: "#FFD700" },
  { id: 23, name: "Silver", color: "bg-slate-300", hex: "#C0C0C0" },
  { id: 24, name: "Burgundy", color: "bg-red-900", hex: "#800020" },
  { id: 25, name: "Khaki", color: "bg-slate-400", hex: "#F0E68C" },
];

export const FABRICS = [
  "Cotton",
  "Linen",
  "Wool",
  "Polyester",
  "Nylon",
  "Silk",
  "Rayon",
  "Acrylic",
  "Denim",
  "Leather",
  "Suede",
  "Corduroy",
  "Jersey",
  "Velvet",
  "Lace",
  "Satin",
  "Cashmere",
  "Fleece",
  "Spandex",
];

export const WEATHER_SUITABILITY = [
  "Hot",
  "Warm",
  "Cool",
  "Cold",
  "Rainy",
  "Snowy",
  "Windy",
  "Humid",
  "Dry",
  "All-Weather",
];

export const STYLE_TAGS = [
  "Casual",
  "Formal",
  "Business Casual",
  "Sporty",
  "Athleisure",
  "Large Wear",
];

export const ETHNICITIES = [
  "African",
  "Afro-Caribbean",
  "African-American",
  "East Asian",
  "Chinese",
  "Japanese",
  "Korean",
  "South Asian",
  "Indian",
  "Pakistani",
  "Bangladeshi",
  "Southeast Asian",
  "Filipino",
  "Thai",
  "Vietnamese",
  "Central Asian",
  "Kazakh",
  "Uzbek",
  "European",
  "Western European",
  "Eastern European",
  "Southern European",
  "Northern European",
  "Middle Eastern",
  "Arab",
  "Persian",
  "Turkish",
  "Caucasian",
  "Hispanic",
  "Latino",
  "Indigenous American",
  "Andean",
  "Mayan",
  "Native American",
  "First Nations (Canada)",
  "Aboriginal (Australia)",
  "Pacific Islander",
  "Maori",
  "Polynesian",
  "Micronesian",
  "Mixed/Multiracial",
  "Other",
];
