export const CLOTHING_TYPES = [
  "Shirt",
  "T-shirt",
  "Blouse",
  "Sweater",
  "Hoodie",
  "Jacket",
  "Coat",
  "Pants",
  "Jeans",
  "Shorts",
  "Skirt",
  "Dress",
  "Suit",
  "Blazer",
  "Vest",
  "Sweatpants",
  "Joggers",
  "Leggings",
  "Cardigan",
  "Tank Top",
  "Polo Shirt",
  "Swimsuit",
  "Scarf",
  "Hat",
  "Gloves",
  "Socks",
  "Shoes",
  "Sandals",
  "Boots",
  "Sneakers",
  "Heels",
  "Flats",
  "Flip-Flops",
];

export const CLOTHING_COLORS = [
  { id: 1, name: "Black", color: "bg-slate-900" },
  { id: 2, name: "White", color: "bg-white" },
  { id: 3, name: "Gray", color: "bg-slate-500" },
  { id: 4, name: "Navy Blue", color: "bg-blue-800" },
  { id: 5, name: "Blue", color: "bg-blue-500" },
  { id: 6, name: "Sky Blue", color: "bg-blue-300" },
  { id: 7, name: "Red", color: "bg-red-500" },
  { id: 8, name: "Maroon", color: "bg-red-800" },
  { id: 9, name: "Pink", color: "bg-pink-400" },
  { id: 10, name: "Hot Pink", color: "bg-pink-500" },
  { id: 11, name: "Purple", color: "bg-purple-500" },
  { id: 12, name: "Lavender", color: "bg-purple-300" },
  { id: 13, name: "Green", color: "bg-green-500" },
  { id: 14, name: "Olive Green", color: "bg-green-800" },
  { id: 15, name: "Yellow", color: "bg-yellow-400" },
  { id: 16, name: "Orange", color: "bg-orange-500" },
  { id: 17, name: "Brown", color: "bg-stone-800" },
  { id: 18, name: "Beige", color: "bg-slate-200" },
  { id: 19, name: "Cream", color: "bg-slate-100" },
  { id: 20, name: "Teal", color: "bg-primary-600" },
  { id: 21, name: "Turquoise", color: "bg-teal-400" },
  { id: 22, name: "Gold", color: "bg-yellow-500" },
  { id: 23, name: "Silver", color: "bg-slate-300" },
  { id: 24, name: "Burgundy", color: "bg-red-900" },
  { id: 25, name: "Khaki", color: "bg-slate-400" },
];

export const FABRICS = [
  "Cotton",
  "Linen",
  "Wool",
  "Polyester",
  "Nylon",
  "Silk",
  "Rayon",
  "Acrylic",
  "Denim",
  "Leather",
  "Suede",
  "Corduroy",
  "Jersey",
  "Velvet",
  "Lace",
  "Satin",
  "Cashmere",
  "Fleece",
  "Spandex",
];

export const WEATHER_SUITABILITY = [
  "Hot",
  "Warm",
  "Cool",
  "Cold",
  "Rainy",
  "Snowy",
  "Windy",
  "Humid",
  "Dry",
  "All-Weather",
];

export const STYLE_TAGS = [
  "Casual",
  "Formal",
  "Business Casual",
  "Sporty",
  "Athleisure",
  // ... reste des styles
];

export const SKIN_COLORS = [
  "Fair",
  "Light",
  "Medium",
  "Olive",
  "Brown",
  "Dark",
  "Tan",
  "Black",
  "Very dark",
];
